### ISSUE TITLE
About the training process

### ISSUE THREAD

**Issue by vietvietsotatek** [PadishahIII/RFGuess#1]
Hello,
Can you provide the source code for training RFGuess?
I'd like to fully understand the training process.

Thank you and best regards.

**Comment by PadishahIII** [comment]
Hi, if you want more detail about this project, refer to [this article](https://www.wolai.com/secnote/aL4Xth452sX4XuSydnpqtj), and a [transcript](https://www.wolai.com/secnote/row4spm7VvaYAkUmxsFQBT), which provides a general introduction of the main algorithm and the training process. If you want to get a view of the source code, just start at the slot function of the below two button:
<img width="1434" alt="image" src="https://github.com/PadishahIII/RFGuess/assets/83501709/bed370ec-4cc2-4710-9566-c761a9cf1853">
